//action types for the state update and to know which type of action has tobe performed.
//every action must have a relavent action type.

const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";
const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

const GET_TASK_FAILURE = "GET_TASK_FAILURE";
const GET_TASK_REQUEST = "GET_TASK_REQUEST";
const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";

const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";
const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

const PATCH_TASK_REQUEST = "PATCH_TASK_REQUEST";
const PATCH_TASK_SUCCESS = "PATCH_TASK_SUCCESS";
const PATCH_TASK_FAILURE = "PATCH_TASK_FAILURE";

export {
  ADD_TASK_FAILURE,
  ADD_TASK_REQUEST,
  ADD_TASK_SUCCESS,
  GET_TASK_FAILURE,
  GET_TASK_REQUEST,
  GET_TASK_SUCCESS,
  DELETE_TASK_FAILURE,
  DELETE_TASK_REQUEST,
  DELETE_TASK_SUCCESS,
  PATCH_TASK_FAILURE,
  PATCH_TASK_REQUEST,
  PATCH_TASK_SUCCESS,
};
